name: hsp2_py311_dev
channels:
  - conda-forge
  - nodefaults # Speeds solving env, by limiting the number of options

dependencies:
  # Aligned with Anaconda 2023.09-0 (Sep 29, 2023)
  # https://docs.anaconda.com/free/anaconda/release-notes/#anaconda-2023-09-0-sep-29-2023
  # package management
  - conda
  - conda-build
  - conda-libmamba-solver
  - pip

  # Running HSP2
  - python =3.11
  - scipy   # Scipy also installs numpy
  - pandas >=2.0  # Pandas installs most scientific Python modules, such as Numpy, etc.
  - numba 
  - numpy 
  - hdf5
  - pytables 
  - h5py 
  - hdf5plugin  # HDF5 compression filters for h5py & jupyterlab_hdf
  # - dask  # for future performance enhancements
  - mando  # for Python CLI app in HSP2tools/HSP2_CLI.py; hasn't been updated since 2017 and doesn't support Python 3.9: https://github.com/rubik/mando

  # Interactivity & Visualization via Jupyter Notebooks (optional, but required for tutorials)
  - jupyterlab # also installs classic Jupyter notbook
  - ipympl  # jupyter-matplotlib, https://github.com/matplotlib/ipympl
  - nodejs    # required for many JupyterLab extensions
  # HoloViz, https://holoviz.org
  - hvplot  # hvPlot installs most HoloViz libs, including matplotlib
  - ipywidgets  # Required for HoloViz interactivity in Jupyter notebooks

  # Dev tools (optional)
  - python-language-server
  - python-lsp-server # LSP extension for Python (pylsp), including:
    # Rope for Completions and renaming
    # Pyflakes linter to detect various errors
    # McCabe linter for complexity checking
    # pycodestyle linter for style checking
    # pydocstyle linter for docstring style checking (disabled by default)
    # autopep8 for code formatting
    # YAPF for code formatting (preferred over autopep8)
    # flake8 for error checking (disabled by default)
    # pylint for code linting (disabled by default)
  - jupyterlab-lsp # Provides both server extension and lab extension


  # PIP install requirements only if it is not possible with conda
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment
  - pip:
